name: unified_ai_sdk
description: A unified, provider-agnostic Dart SDK for interacting with multiple AI providers through a single, consistent interface.
version: 0.0.1
homepage: https://github.com/prakashvidya68/unified_ai_sdk
repository: https://github.com/prakashvidya68/unified_ai_sdk/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  http: ^1.2.0
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.10.0
  lints: ^6.0.0
  mockito: ^5.5.0
  test: ^1.25.6
