name: unified_ai_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  meta: ^1.12.0
  objectbox: ^5.0.0

dev_dependencies:
  build_runner: ^2.10.0
  lints: ^6.0.0
  mockito: ^5.5.0
  test: ^1.25.6
